language: csharp

solution: GPUVerify.sln

env:
  global:
    - LLVM_VERSION=6.0
    - LLVM_FULL_VERSION="${LLVM_VERSION}.0"
    - Z3_VERSION=4.6.0
    - CVC4_VERSION=1.5
    - CLONE_DEPTH=50
    - BUILD_ROOT="${TRAVIS_BUILD_DIR}"

cache:
  directories:
    - $TRAVIS_BUILD_DIR/downloads

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
    packages:
      - g++-4.9
      - ninja-build
      - python-psutil
      # From sources above
      - llvm-6.0-dev
      - clang-6.0
      - clang-6.0-dev

jobs:
  include:
    - stage: test
      os: linux
      dist: trusty
      sudo: false
      env:
        - DEFAULT_SOLVER=z3
        - Z3="z3-${Z3_VERSION}-x64-ubuntu-14.04"
      script:
        - export CXX=g++-4.9
        - ${BUILD_ROOT}/.travis/travis_build_and_test.sh
    - os: linux
      dist: trusty
      sudo: false
      env:
        - DEFAULT_SOLVER=cvc4
        - CVC4="cvc4-${CVC4_VERSION}-x86_64-linux-opt"
      script:
        - export CXX=g++-4.9
        - ${BUILD_ROOT}/.travis/travis_build_and_test.sh
    - os: linux
      dist: trusty
      sudo: false
      if: (branch = master OR tag IS present) AND type = push
      env:
        - DEFAULT_SOLVER=z3
        - Z3="z3-${Z3_VERSION}-x64-ubuntu-14.04"
        - LLVM="clang+llvm-${LLVM_FULL_VERSION}-x86_64-linux-gnu-ubuntu-14.04"
      script:
        - export CXX="clang++-${LLVM_VERSION}"
        - ${BUILD_ROOT}/.travis/travis_build_and_test.sh
    - os: linux
      dist: trusty
      sudo: false
      if: (branch = master OR tag IS present) AND type = push
      env:
        - DEFAULT_SOLVER=cvc4
        - CVC4="cvc4-${CVC4_VERSION}-x86_64-linux-opt"
        - LLVM="clang+llvm-${LLVM_FULL_VERSION}-x86_64-linux-gnu-ubuntu-14.04"
      script:
        - export CXX="clang++-${LLVM_VERSION}"
        - ${BUILD_ROOT}/.travis/travis_build_and_test.sh
    - stage: deploy
      os: linux
      dist: trusty
      sudo: false
      if: tag IS present AND type = push AND repo = mc-imperial/gpuverify
      env:
        - DEFAULT_SOLVER=z3
        - Z3="z3-${Z3_VERSION}-x64-ubuntu-14.04"
        - CVC4="cvc4-${CVC4_VERSION}-x86_64-linux-opt"
        - LLVM="clang+llvm-${LLVM_FULL_VERSION}-x86_64-linux-gnu-ubuntu-14.04"
        - DEPLOY_DIR="${TRAVIS_TAG}"
      script:
        - export CXX="clang++-${LLVM_VERSION}"
        - ${BUILD_ROOT}/.travis/travis_build_and_deploy.sh
      deploy:
        provider: releases
        api_key:
          secure: P9dRk7UF9s+Q1mXzyEDRjwcy+pcWhCd2g2R785rtA6RdAZkHbp45CU7gjS2uuzpE0Faodw11yHQ9vTn2oeEsTx+T4AVR9CfL3EIPM2rvRAkusLabqebnDz+41+mJEHRr9cKRumsas6ic6wwydBCMMW9aj5i0xPza6xdqD9t2Fek=
        file:
          - GPUVerifyLinux64.zip
          - libclc.zip
        skip_cleanup: true
        on:
          tags: true

stages:
  - test
  - deploy
