#!/bin/bash

INSTALL_DIR=/vol/multicore/afd/GPUVerifyInstall
LIBCLC_DIR=/vol/multicore/afd/libclc
BUGLE_DIR=/vol/multicore/afd/bugle
BUGLE_BIN_DIR=/vol/multicore/afd/bugle-build
LLVM_BUILD_DIR=/vol/multicore/afd/llvm-build
LLVM_BIN_DIR=/vol/multicore/afd/llvm-build/Release+Asserts/bin
GPUVERIFY_VCGEN_BIN_DIR=/vol/multicore/afd/gpuverify/GPUVerify/bin/Release
GPUVERIFY_BOOGIE_DRIVER_BIN_DIR=/vol/multicore/afd/gpuverify/GPUVerifyBoogieDriver/bin/Release
Z3_BIN_DIR=/vol/multicore/afd/z3/bin

mkdir $INSTALL_DIR

cp -r $LIBCLC_DIR $INSTALL_DIR/libclc

mkdir $INSTALL_DIR/bugle

cp -r $BUGLE_DIR/include-blang $INSTALL_DIR/bugle/include-blang

cp -r $LLVM_BUILD_DIR/Release+Asserts/lib $INSTALL_DIR/lib

cp GPUVerify.py $INSTALL_DIR

mkdir $INSTALL_DIR/bin

cp $LLVM_BIN_DIR/clang $INSTALL_DIR/bin
cp $LLVM_BIN_DIR/opt $INSTALL_DIR/bin
cp $BUGLE_BIN_DIR/bugle $INSTALL_DIR/bin

cp $GPUVERIFY_BOOGIE_DRIVER_BIN_DIR/AbsInt.dll $INSTALL_DIR/bin
cp $GPUVERIFY_BOOGIE_DRIVER_BIN_DIR/Provers.SMTLib.dll $INSTALL_DIR/bin
cp $GPUVERIFY_BOOGIE_DRIVER_BIN_DIR/Basetypes.dll $INSTALL_DIR/bin
cp $GPUVERIFY_BOOGIE_DRIVER_BIN_DIR/CodeContractsExtender.dll $INSTALL_DIR/bin
cp $GPUVERIFY_BOOGIE_DRIVER_BIN_DIR/Graph.dll $INSTALL_DIR/bin
cp $GPUVERIFY_BOOGIE_DRIVER_BIN_DIR/VCExpr.dll $INSTALL_DIR/bin
cp $GPUVERIFY_BOOGIE_DRIVER_BIN_DIR/Core.dll $INSTALL_DIR/bin
cp $GPUVERIFY_BOOGIE_DRIVER_BIN_DIR/Houdini.dll $INSTALL_DIR/bin
cp $GPUVERIFY_BOOGIE_DRIVER_BIN_DIR/VCGeneration.dll $INSTALL_DIR/bin
cp $GPUVERIFY_BOOGIE_DRIVER_BIN_DIR/Model.dll $INSTALL_DIR/bin
cp $GPUVERIFY_BOOGIE_DRIVER_BIN_DIR/ParserHelper.dll $INSTALL_DIR/bin
cp $GPUVERIFY_BOOGIE_DRIVER_BIN_DIR/UnivBackPred2.smt2 $INSTALL_DIR/bin
cp $GPUVERIFY_BOOGIE_DRIVER_BIN_DIR/GPUVerifyBoogieDriver.exe $INSTALL_DIR/bin

cp $GPUVERIFY_VCGEN_BIN_DIR/GPUVerifyVCGen.exe $INSTALL_DIR/bin
cp $GPUVERIFY_VCGEN_BIN_DIR/Predication.dll $INSTALL_DIR/bin

cp $Z3_BIN_DIR/z3 $INSTALL_DIR/bin

ln $INSTALL_DIR/bin/z3 $INSTALL_DIR/bin/z3.exe

